"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ExternalLink, Code, Database, Cpu, Activity, Layout, Code2, X, Play } from "lucide-react";
import { useLanguage } from "@/context/LanguageContext";

const GITHUB_BASE = "https://github.com/italobotelho/";

const projectLinks: Record<string, { github: string; live?: string }> = {
  "siest": { github: `${GITHUB_BASE}siest-app`, live: "https://siest-app.vercel.app" },
  "8-puzzle": { github: `${GITHUB_BASE}8-puzzle-solver-ai` },
  "casa de maria": { github: `${GITHUB_BASE}casa-de-maria-v2` },
  "genetic": { github: `${GITHUB_BASE}genetic-algorithm-nqueens` },
  "cesta": { github: `${GITHUB_BASE}cesta_basica` },
  "imrs": { github: `${GITHUB_BASE}imrs_educacao_2020` }
};

export function Portfolio() {
  const { t } = useLanguage();
  const [activeIframe, setActiveIframe] = useState<string | null>(null);

  const getProjectLinks = (title: string) => {
    const titleLower = title.toLowerCase();
    if (titleLower.includes("siest")) return projectLinks["siest"];
    if (titleLower.includes("8-puzzle")) return projectLinks["8-puzzle"];
    if (titleLower.includes("casa de maria")) return projectLinks["casa de maria"];
    if (titleLower.includes("genetic")) return projectLinks["genetic"];
    if (titleLower.includes("cesta")) return projectLinks["cesta"];
    if (titleLower.includes("imrs")) return projectLinks["imrs"];
    return { github: "#" };
  };

  const getWatermarkIcon = (title: string) => {
    const titleLower = title.toLowerCase();
    if (titleLower.includes("siest")) return <Activity className="w-full h-full text-neon-blue" strokeWidth={0.5} />;
    if (titleLower.includes("casa")) return <Layout className="w-full h-full text-neon-pink" strokeWidth={0.5} />;
    if (titleLower.includes("genetic") || titleLower.includes("puzzle")) return <Cpu className="w-full h-full text-neon-blue" strokeWidth={0.5} />;
    if (titleLower.includes("cesta") || titleLower.includes("imrs")) return <Database className="w-full h-full text-neon-pink" strokeWidth={0.5} />;
    return <Code2 className="w-full h-full text-white" strokeWidth={0.5} />;
  };

  return (
    <div id="portfolio" className="w-full">
      {/* Introduction Screen for Portfolio */}
      <section className="h-screen w-full snap-start flex items-center justify-center relative overflow-hidden bg-[#050505]">
        <div className="absolute inset-0 bg-gradient-to-b from-[#0d1117] to-black opacity-80" />
        <div className="absolute top-1/4 left-1/4 w-[500px] h-[500px] bg-neon-blue/10 rounded-full blur-[120px] pointer-events-none" />
        <div className="absolute bottom-1/4 right-1/4 w-[500px] h-[500px] bg-neon-pink/10 rounded-full blur-[120px] pointer-events-none" />
        
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="relative z-10 text-center px-6"
        >
          <h2 className="font-heading text-5xl md:text-7xl font-bold mb-6 text-white tracking-tighter">
            {t.portfolio.title}
          </h2>
          <p className="text-xl text-neutral-400 font-light tracking-wide">
            {t.portfolio.scroll}
          </p>
        </motion.div>
      </section>

      {/* Full Screen Projects */}
      {t.portfolio.projects.map((project, index) => {
        const links = getProjectLinks(project.title);
        const isActive = activeIframe === project.title;
        const isEven = index % 2 === 0;

        return (
          <section
            key={project.title}
            className="h-screen w-full snap-start relative flex items-center overflow-hidden bg-black"
          >
            {/* Dynamic Background generated by CSS (Fallback when iframe is not active) */}
            <div className="absolute inset-0 z-0">
              <div className={`absolute inset-0 bg-gradient-to-br ${isEven ? 'from-neon-blue/5 to-black' : 'from-neon-pink/5 to-black'} opacity-50`} />
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] opacity-10 pointer-events-none transform -rotate-12">
                {getWatermarkIcon(project.title)}
              </div>
            </div>

            {/* Interactive Iframe */}
            <AnimatePresence>
              {isActive && links.live && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.5 }}
                  className="absolute inset-0 z-10 bg-black"
                >
                  <iframe 
                    src={links.live} 
                    className="w-full h-full border-none"
                    title={project.title}
                    sandbox="allow-scripts allow-same-origin allow-popups"
                  />
                  <button
                    onClick={() => setActiveIframe(null)}
                    className="absolute top-6 right-6 z-50 p-3 bg-red-500/20 hover:bg-red-500/80 backdrop-blur-md rounded-full text-red-100 transition-all border border-red-500/30 hover:border-red-500 hover:scale-110"
                  >
                    <X className="w-6 h-6" />
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Content Panel (Glassmorphism) */}
            <div className={`relative z-20 w-full max-w-7xl mx-auto px-6 lg:px-12 flex ${isActive ? 'items-end pb-12 pointer-events-none' : 'items-center'} transition-all duration-700 h-full`}>
              <motion.div
                initial={{ opacity: 0, x: isEven ? -50 : 50 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.8 }}
                className={`
                  glass p-8 md:p-12 rounded-3xl border border-white/10 shadow-2xl backdrop-blur-xl 
                  transition-all duration-700 
                  ${isActive 
                    ? 'max-w-xl bg-black/40 hover:bg-black/80 pointer-events-auto transform scale-90 origin-bottom-left' 
                    : 'max-w-2xl bg-[#0a0a0a]/60'
                  }
                `}
              >
                <h3 className="font-heading text-4xl md:text-5xl font-bold text-white mb-4 tracking-tight">
                  {project.title}
                </h3>
                
                <p className={`text-neutral-300 leading-relaxed mb-8 ${isActive ? 'line-clamp-2 text-sm' : 'text-lg'}`}>
                  {project.description}
                </p>

                <div className={`flex flex-wrap gap-2 mb-8 ${isActive ? 'hidden' : 'flex'}`}>
                  {project.tags.map(tag => (
                    <span key={tag} className="text-sm font-mono font-medium text-neon-blue bg-neon-blue/10 px-4 py-2 rounded-lg border border-neon-blue/20">
                      {tag}
                    </span>
                  ))}
                </div>

                <div className="flex items-center gap-4 mt-auto">
                  {links.live ? (
                    <button 
                      onClick={() => {
                        if (isActive) {
                          window.open(links.live, '_blank');
                          setActiveIframe(null);
                        } else {
                          setActiveIframe(project.title);
                        }
                      }}
                      className={`
                        flex items-center justify-center gap-3 font-heading tracking-widest rounded-xl transition-all pointer-events-auto
                        ${isActive 
                          ? 'px-6 py-4 bg-white/10 text-white hover:bg-neon-blue hover:border-neon-blue hover:text-black border border-white/20 hover:scale-105' 
                          : 'px-8 py-4 bg-neon-blue text-black hover:bg-white hover:scale-105 shadow-[0_0_20px_var(--color-neon-blue)]'
                        }
                      `}
                    >
                      {isActive ? (
                        <><ExternalLink className="w-5 h-5" /> NEW TAB</>
                      ) : (
                        <><Play className="w-5 h-5 fill-current" /> LIVE PREVIEW</>
                      )}
                    </button>
                  ) : (
                    <span className="px-6 py-3 bg-white/5 rounded-xl text-neutral-500 font-mono text-sm border border-white/5 cursor-not-allowed">
                      Live coming soon
                    </span>
                  )}
                  
                  <a 
                    href={links.github} 
                    target="_blank" 
                    rel="noreferrer" 
                    className={`flex items-center gap-2 px-6 py-4 rounded-xl font-heading text-white border border-white/10 hover:border-white/40 hover:bg-white/5 transition-all ${isActive && 'pointer-events-auto'}`}
                  >
                    <Code className="w-5 h-5" /> GITHUB
                  </a>
                </div>
              </motion.div>
            </div>
          </section>
        );
      })}
    </div>
  );
}
